apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        secret_key: "{{ .secret_key }}"
        bootstrap_email: "{{ .bootstrap_email }}"
        bootstrap_password: "{{ .bootstrap_password }}"
  data:
    - secretKey: username
      remoteRef:
        key: homelab/authentik/authentik-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: homelab/authentik/authentik-credentials
        property: password
    - secretKey: secret_key
      remoteRef:
        key: homelab/authentik/authentik-credentials
        property: secret_key
    - secretKey: bootstrap_email
      remoteRef:
        key: homelab/authentik/authentik-credentials
        property: bootstrap_email
    - secretKey: bootstrap_password
      remoteRef:
        key: homelab/authentik/authentik-credentials
        property: bootstrap_password