# Vault source path: homelab/baserow/postgresql
# Required properties at that path: username, password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: baserow-db
  namespace: baserow
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: baserow-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_USER: "{{ .username }}"
        DATABASE_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: homelab/baserow/postgresql
        property: username
    - secretKey: password
      remoteRef:
        key: homelab/baserow/postgresql
        property: password
