apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-dns01-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-dns01-api-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        api-token: "{{ .api_token }}"
  data:
    - secretKey: api_token
      remoteRef:
        key: homelab/cert-manager/cloudflare-dns01-api-token
        property: api_token
