apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui-db
  namespace: open-webui
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: open-webui-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: homelab/open-webui/postgresql
        property: username
    - secretKey: password
      remoteRef:
        key: homelab/open-webui/postgresql
        property: password
