# Vault source path: homelab/wger/postgresql
# Required properties at that path: username, password, database
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wger-db
  namespace: wger
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wger-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        USERDB_USER: "{{ .username }}"
        USERDB_PASSWORD: "{{ .password }}"
        USERDB_NAME: "{{ .database }}"
  data:
    - secretKey: username
      remoteRef:
        key: homelab/wger/postgresql
        property: username
    - secretKey: password
      remoteRef:
        key: homelab/wger/postgresql
        property: password
    - secretKey: database
      remoteRef:
        key: homelab/wger/postgresql
        property: database