apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-admin
  namespace: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgresql-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgresql/postgresql-admin
        property: username
    - secretKey: password
      remoteRef:
        key: postgresql/postgresql-admin
        property: password