apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openwrt-ap-auth
  namespace: openwrt-ops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openwrt-ap-auth
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: host
      remoteRef:
        key: homelab/openwrt/ap
        property: host
    - secretKey: port
      remoteRef:
        key: homelab/openwrt/ap
        property: port
    - secretKey: username
      remoteRef:
        key: homelab/openwrt/ap
        property: username
    - secretKey: ssh_private_key
      remoteRef:
        key: homelab/openwrt/ap
        property: ssh_private_key
    - secretKey: mesh_key
      remoteRef:
        key: homelab/openwrt/ap
        property: mesh_key
