# values/pgadmin/values.yaml

# Use the official pgAdmin image with specific version
image:
  repository: dpage/pgadmin4
  tag: "9.13"
  pullPolicy: IfNotPresent

existingSecret: pgadmin-admin
existingSecretEmailKey: email
existingSecretPasswordKey: password

# This sections is for maintining the sticky session cookie secret key, which is required for pgAdmin to function properly. It should be the same as the one stored in Vault and referenced in the ExternalSecret.
env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: pgadmin-admin
        key: secret_key

# Persistence Configuration (Using Longhorn as per your cluster setup)
persistence:
  enabled: true
  storageClass: "longhorn"
  size: 4Gi
  accessMode: ReadWriteOnce

# Ingress Configuration (Traefik + Cert-Manager)
ingress:
  enabled: true
  className: "my-traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/affinity: cookie # Enables sticky sessions to prevent CSRF issues.
  hosts:
    - host: pgadmin.dklair.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: pgadmin-tls
      hosts:
        - pgadmin.dklair.io

# Resources (Optional, good for K3s)
resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi