# Keep Longhorn components schedulable on all nodes, including tainted control-plane nodes.
global:
  nodeSelector: {}
  tolerations:
    - key: homelab.io/control-infra
      operator: Equal
      value: "true"
      effect: NoSchedule

defaultSettings:
  taintToleration: homelab.io/control-infra=true:NoSchedule
  systemManagedComponentsNodeSelector: ""

ingress:
  enabled: true
  ingressClassName: my-traefik
  host: longhorn.dklair.io
  tls: true
  tlsSecret: longhorn-tls
  path: /
  pathType: ImplementationSpecific
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik-forward-auth@kubernetescrd
