# Keep Longhorn components schedulable on all nodes, including tainted control-plane nodes.
global:
  nodeSelector: {}
  tolerations:
    - key: homelab.io/control-infra
      operator: Equal
      value: "true"
      effect: NoSchedule

defaultSettings:
  taintToleration: homelab.io/control-infra=true:NoSchedule
  systemManagedComponentsNodeSelector: ""
