cluster:
  name: postgresql
  instances: 1

  storage:
    size: 10Gi
    storageClass: longhorn

  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      secret:
        name: postgresql-admin
        userKey: username
        passwordKey: password

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"