apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: test-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: homelab/test-secret
        property: username
    - secretKey: password
      remoteRef:
        key: homelab/test-secret
        property: password