apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://192.168.4.177:8200"
      path: "homelab"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "homelab-role"
          serviceAccountRef:
            name: "vault-auth"
            namespace: "secrets"