# when the PGadmin application is deployed, it seems to install and launch perfectly fine. However when I
# try to access the pgadmin web interface, I get a wrong username or password error.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    # 1. The Helm Chart Source
    - repoURL: https://helm.runix.net
      chart: pgadmin4
      targetRevision: 1.59.0
      helm:
        valueFiles:
          - $values/values/pgadmin/values.yaml
    # 2. The Values File Source (Your Repo)
    - repoURL: https://github.com/el-dragon-1/homelab_dklair.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true