apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baserow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - repoURL: https://baserow.github.io/baserow-chart
      chart: baserow
      targetRevision: 1.0.52
      helm:
        valueFiles:
          - $values/values/baserow/values.yaml
        parameters:
          - name: migration.enabled
            value: "false"
          - name: backendConfigMap.MIGRATE_ON_STARTUP
            value: "true"
    - repoURL: https://github.com/el-dragon-1/homelab_dklair.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/el-dragon-1/homelab_dklair.git
      targetRevision: HEAD
      path: apps/baserow
  destination:
    server: https://kubernetes.default.svc
    namespace: baserow
  ignoreDifferences:
    - kind: Secret
      name: baserow-minio
      namespace: baserow
      jsonPointers:
        - /data
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
