apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-ai
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - repoURL: https://go-skynet.github.io/helm-charts/
      chart: local-ai
      targetRevision: 3.4.2
      helm:
        valueFiles:
          - $values/values/local-ai/values.yaml
    - repoURL: https://github.com/el-dragon-1/homelab_dklair.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: local-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true