apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Sync after external-secrets creates the secret
spec:
  project: default
  sources:
    # 1. The Helm Chart Source
    - repoURL: https://otwld.github.io/pgadmin4-helm-chart/
      chart: pgadmin4
      targetRevision: 4.2.0 # Compatible with pgAdmin 9.x
      helm:
        valueFiles:
          - $values/values/pgadmin/values.yaml
    # 2. The Values File Source (Your Repo)
    - repoURL: https://github.com/el-dragon-1/homelab_dklair.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true