# apps/external-secrets-config/pgadmin-admin-externalsecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-admin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Ensure this syncs before the Helm app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-admin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        email: "{{ .email }}"
        password: "{{ .password }}"
  data:
    - secretKey: email
      remoteRef:
        key: pgadmin/pgadmin-admin
        property: email
    - secretKey: password
      remoteRef:
        key: pgadmin/pgadmin-admin
        property: password