apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - repoURL: https://k8s-at-home.com/charts/
      chart: wireguard
      targetRevision: 1.4.2
      helm:
        valueFiles:
          - $values/values/wireguard/values.yaml
    - repoURL: https://github.com/el-dragon-1/homelab_dklair.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: wireguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
